name: 'enterprise_dwh'
version: '1.0.0'
config-version: 2

profile: 'enterprise_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  enterprise_dwh:
    +schema: warehouse

    stage:
      +materialized: view

    marts:
      dimension: {}

      fact: {}

      sales: {}

      marketing: {}

snapshots:
  enterprise_dwh:
    +target_schema: warehouse